### ISSUE TITLE
graphql-anywhere description enhancement

### ISSUE THREAD

**Issue by Xample** [apollostack/graphql-anywhere#9]
I do not completely get the idea behind graphql-anywhere. Would it be suitable to have a pure client side graphQL resolver ? Which one could directly talk to custom rest API ? Could you give a use case example in the readme.md ?

**Comment by stubailo** [comment]
There are tons of examples in the README already. It's designed specifically for those things.

You can access REST APIs from the client using regular graphql-js, you don't need this package for that: https://github.com/graphql/graphql-js

**Comment by linonetwo** [comment]
I think this package provide a new way to collect data. By define resolvers by yourself, you can query anything with graphql.

We used to get data from Redux by writing simple 

```javascript
@connect(state => ({ token: state.auth.token })
class Blabla extends Component {

} 
```

But If data in the Redux store is also heavily nested, this package may need to be put into battle.

@stubailo Is that correct?

**Comment by stubailo** [comment]
@linonetwo that's about right. I'm going to close this issue since it's pretty old and if the README can be improved a PR might be a good idea.

**Comment by linonetwo** [comment]
@stubailo I'm waiting normalizer to be commonly used. But I have a question.

As
http://blog.isquaredsoftware.com/2016/10/practical-redux-part-1-redux-orm-basics/
Said, If you use normalizer to store data, you can use redux-orm.

And I think graphql-anywhere is better, but if we are using apollo-client, seems we don't need normalizer anymore. Since there is no data stored in the redux store.

**Comment by linonetwo** [comment]
@stubailo I'm waiting normalizer to be commonly used. But I have a question.

As
http://blog.isquaredsoftware.com/2016/10/practical-redux-part-1-redux-orm-basics/
Said, If you use normalizer to store data, you can use redux-orm.

And I think graphql-anywhere is better, but if we are using apollo-client, seems we don't need normalizer anymore. Since there is no data stored in the redux store.

**Comment by stubailo** [comment]
@linonetwo actually all of Apollo Client is based on this library, so you are in fact using it :]
